// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zzxncvhtxnflhuvpcidr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp6eG5jdmh0eG5mbGh1dnBjaWRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczNTkwOTMsImV4cCI6MjA3MjkzNTA5M30.y_uuaYFKpl5d8f08-P_seeHOSDvtkLE5XPIgZ7U_O7o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});